#we will customize our request and retrieve a Swedish version of the Debian home page...
#1st wee always start with a    by creating a REQUEST OBJECT...
from urllib.request import Request, urlopen
req = Request('http://www.debian.org')
#next we add the header request...
req.add_header('Accept-Language', 'sv')
#the add_header method takes the name of the headerr and the contents of the header as arguements
#Lastly submit the customized request with urlopen()...
response = urlopen(req)
#check the response.
print(response.readlines()[:9])